<a href="https://colab.research.google.com/github/SaidurIUT/ML-Lab-2A---CSE-4622/blob/main/210041132_Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab Task 01

## NumPy

In [1]:
import numpy as np

### Task 1

Create an ndarray x of shape= (5, 4) with random numbers – Each of the 5 rows
represents a sample with 4 features

In [2]:
x = np.random.rand(5, 4)  # values between 0 and 1
print("Feature matrix x:\n", x)


Feature matrix x:
 [[0.38269111 0.61378638 0.47304689 0.72243849]
 [0.11094459 0.5438314  0.72465051 0.68228474]
 [0.36677824 0.05798195 0.65215455 0.318403  ]
 [0.34074043 0.65725522 0.8465155  0.4903555 ]
 [0.38839665 0.09770874 0.66938792 0.68302004]]


### Task 2

Create a flat ndarray y of shape=(5, ), whose elements are 0 and 1 – Each element is
the class label of the corresponding sample in x [Hint: use np.random.rand(...) and
np.random.randint(...)]

In [4]:
y = np.random.randint(0, 2, size=5)
print("Label vector y:", y)

Label vector y: [1 0 0 0 0]


### Task 3

Define a function extract_subset(x, y, y0) that takes as input: – the feature matrix
x, and the labels y from the previous exercise – a target class y0 (i.e., either y0=0 or
y0=1) and returns a feature matrix containing only samples belonging to y0

In [5]:
def extract_subset(x, y, y0):
    return x[y == y0]

In [6]:
# Example usage:
subset_0 = extract_subset(x, y, 0)
print("Subset with class 0:\n", subset_0)

Subset with class 0:
 [[0.11094459 0.5438314  0.72465051 0.68228474]
 [0.36677824 0.05798195 0.65215455 0.318403  ]
 [0.34074043 0.65725522 0.8465155  0.4903555 ]
 [0.38839665 0.09770874 0.66938792 0.68302004]]


### Task 4

Import a dataset (IRIS dataset) by keeping the text and numbers intact. url =
"https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"


In [7]:
iris_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris_data = np.genfromtxt(iris_url, delimiter=',', dtype='str')
print("IRIS Dataset (first 5 rows):\n", iris_data[:5])

IRIS Dataset (first 5 rows):
 [['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']]


### Task 5

Find the mean, median and standard deviation of the 1st column of the given dataset.
Give statistical summary of the dataset as many as possible.

In [8]:
iris_numeric = iris_data[:, :4].astype(float)  # first 4 columns are numeric
first_col = iris_numeric[:, 0]

print("Mean:", np.mean(first_col))
print("Median:", np.median(first_col))
print("Standard Deviation:", np.std(first_col))

Mean: 5.843333333333334
Median: 5.8
Standard Deviation: 0.8253012917851409


In [11]:
# Optional: Full statistical summary

for i in range(iris_numeric.shape[1]):
    col = iris_numeric[:, i]
    print(f"\nFeature {i+1} stats:")
    print(f"Mean: {np.mean(col):.2f}, Median: {np.median(col):.2f}, Std: {np.std(col):.2f}")



Feature 1 stats:
Mean: 5.84, Median: 5.80, Std: 0.83

Feature 2 stats:
Mean: 3.05, Median: 3.00, Std: 0.43

Feature 3 stats:
Mean: 3.76, Median: 4.35, Std: 1.76

Feature 4 stats:
Mean: 1.20, Median: 1.30, Std: 0.76


## Pandas

In [24]:
import pandas as pd

### Task 1

Loading & Inspecting Data


*   Load a CSV file into a Pandas DataFrame.
*   Display the first 10 rows.
*   Check the data types of each column.
*   Print summary statistics of numerical columns.




In [25]:
# Load and Inspect Data
file_path = "/content/sample_data/california_housing_test.csv"
df = pd.read_csv(file_path)

In [26]:
# Display the first 10 rows
print(df.head(10))

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   
5    -119.56     36.51                37.0       1018.0           213.0   
6    -121.43     38.63                43.0       1009.0           225.0   
7    -120.65     35.48                19.0       2310.0           471.0   
8    -122.84     38.40                15.0       3080.0           617.0   
9    -118.02     34.08                31.0       2402.0           632.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990        

In [27]:
# Check data types of each column
print("\nData types:")
print(df.dtypes)


Data types:
longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object


In [28]:
# Summary statistics of numerical columns
print("\nSummary statistics:")
print(df.describe())


Summary statistics:
         longitude    latitude  housing_median_age   total_rooms  \
count  3000.000000  3000.00000         3000.000000   3000.000000   
mean   -119.589200    35.63539           28.845333   2599.578667   
std       1.994936     2.12967           12.555396   2155.593332   
min    -124.180000    32.56000            1.000000      6.000000   
25%    -121.810000    33.93000           18.000000   1401.000000   
50%    -118.485000    34.27000           29.000000   2106.000000   
75%    -118.020000    37.69000           37.000000   3129.000000   
max    -114.490000    41.92000           52.000000  30450.000000   

       total_bedrooms    population  households  median_income  \
count     3000.000000   3000.000000  3000.00000    3000.000000   
mean       529.950667   1402.798667   489.91200       3.807272   
std        415.654368   1030.543012   365.42271       1.854512   
min          2.000000      5.000000     2.00000       0.499900   
25%        291.000000    780.000000 

### Task 2

Handling Missing Data

* Identify columns with missing values and count them.
* Remove rows with missing values.
* Fill missing values with the mean or mode.

In [29]:
# Handling Missing Data
missing = df.isnull().sum()
print("Missing values per column:\n", missing)

Missing values per column:
 longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64


In [30]:
# Remove rows with missing values
df_no_na = df.dropna()
print(f"Shape after dropping missing rows: {df_no_na.shape}")

Shape after dropping missing rows: (3000, 9)


In [31]:
# Fill missing values with mean (if any)
df_filled = df.fillna(df.mean(numeric_only=True))
print("Filled missing values with mean.")

Filled missing values with mean.


### Task 3

Suppose you are an investor and want to invest in housing properties. Use this dataset
to make decision on the location of investing.

In [32]:
# Investment Decision - Example Insight
# Let's assume a strategy: invest where 'median_house_value' is high and 'median_income' is high
top_locations = df[df['median_income'] > 6].sort_values(by='median_house_value', ascending=False)
print("Top investment locations:\n", top_locations[['longitude', 'latitude', 'median_income', 'median_house_value']].head(10))

Top investment locations:
       longitude  latitude  median_income  median_house_value
2999    -119.63     34.42         8.5608            500001.0
2992    -122.33     37.39         6.2263            500001.0
42      -118.06     34.15        15.0001            500001.0
2810    -118.16     34.13         7.7230            500001.0
2960    -117.89     33.60         7.8164            500001.0
337     -117.97     34.15         6.4576            500001.0
290     -122.40     37.59         6.2306            500001.0
308     -118.40     34.04         8.5938            500001.0
2683    -118.05     34.14         8.9728            500001.0
2665    -118.39     34.12         8.2816            500001.0
